### ISSUE TITLE
Does not work explanation needed 

### ISSUE THREAD

**Issue by ber5ien** [chornij/yii2-zeroclipboard#3]
Hi Boss,

I have tried to using this extension but it does work for me by some reason.
Please can you advise. I am using it the following way

<?= chornij\zeroclipboard\Button::widget([
    'label' => '<span class="glyphicon glyphicon-copy"></span> ' . \Yii::t('app', 'Copy'),
    'encodeLabel' => false,
    'text' => "$('.copy-selector').text()",
]) ?>

<div class="copy-selector">
LOL
</div>

but it does not copy anything.

Many Thanks.

**Comment by chornij** [comment]
Hello.

I use it like:
```
<?= chornij\zeroclipboard\Button::widget([
    'label' => '<i class="fa fa-copy"></i> ' . \Yii::t('app', 'Copy'),
    'encodeLabel' => false,
    'text' => "$('.xml.hljs').text()",
]) ?>
```
Check your text selector

**Comment by ber5ien** [comment]
Hi,

Many thanks for your reply? is the below correct then ?
        <?= Html::a( 'Back', Yii::$app->request->referrer, ['class' => 'btn btn-primary pull-right']) ?>
      <?= chornij\zeroclipboard\Button::widget([
                            'label' => '<i class="fa fa-copy"></i> ' . \Yii::t('app', 'Copy'),
                            'encodeLabel' => false,
                            'text' => "$('demo-container').text()",
            ]) ?>
    </p>

<div class='demo-container'>
dda
</div>

I does not copy anything.

Do I need to include any extra files js/jQuery or anything on this specific view?
Do i need to have any special plugin enabled in Chrome or something?

**Comment by ber5ien** [comment]
i noticed now that in IE it shows copied once pressed the status does not change in chrome at all.
I noticed the following that the flash was disabled in my Chrome:

chrome://plugins/ and i had disabled the Adobe Flash Player - Version: 19.0.0.185
Shockwave Flash 19.0 r0

Perhahps something to add to readme so people can check it in case of issues :) 

Many Thanks
Raf

**Comment by ber5ien** [comment]
The following now worked fine :)

**Comment by chornij** [comment]
Glad that figured
